services:
  postgres:
    image: postgres:16-alpine
    container_name: banco_digital_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banco_digital
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: banco_digital_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: banco_digital_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banco_digital_app
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: production

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: banco_digital

      REDIS_HOST: redis
      REDIS_PORT: 6379

      ES_NODE: http://elasticsearch:9200

    depends_on:
      postgres:
        condition: service_healthy

    command: sh -c "
      echo 'Waiting for DB...' &&
      sleep 5 &&
      npm run migration:run:prod &&  
      node dist/main.js"

volumes:
  postgres_data:
  redis_data:
  es_data: